apiVersion: apps/v1
kind: Deployment
metadata:
  name: srebootcamp
  labels:
    app: srebootcamp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srebootcamp
  template:
    metadata:
      labels:
        app: srebootcamp 
    spec: 
      containers:
      - name: nginx 
        image: gcr.io/absolute-realm-322617/my-web-server:version1
        imagePullPolicy: Always
        resources: 
          limits:                 
            cpu: "1"
          requests:
            cpu: "0.5"
        ports: 
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: srebootcamp
spec:
  type: LoadBalancer
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: srebootcamp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---

apiVersion: autoscaling/v2beta2 # autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-web-server-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: srebootcamp
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  #targetCPUUtilizationPercentage: 10
