apiVersion: apps/v1
kind: Deployment
metadata:
  name: srebootcamp
  labels:
    app: srebootcamp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srebootcamp
  template:
    metadata:
      labels:
        app: srebootcamp
    spec:
      containers:
      - name: nginx
        image: gcr.io/absolute-realm-322617/sreflaskapp
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.1"
        ports:
        - containerPort: 9090
         env:
          - name: SERVICE_PORT
            value: "9090"
          - name: PROTOCOL
            value: "http"
          #  value: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: srebootcamp
spec:
  type: LoadBalancer
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: srebootcamp
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
    #nodePort: 31313
---


apiVersion: autoscaling/v2beta2 # autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-web-server-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: srebootcamp
    apiVersion: apps/v1
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  #targetCPUUtilizationPercentage: 10
